#ifndef BINDINGS_GLSL
#define BINDINGS_GLSL
#define CAM_BINDING 0
#define LIGHTS_BINDING 1
#define MATERIAL_BINDING 2
#define SCENE_OBJECT_BINDING 3
#define TEXTURE_REFS_BINDING 4
#define BOUNDS_BINDING 5
#define TRIANGLES_BINDING 6
#define VERTICES_BINDING 7

#endif // BINDINGS_GLSL
