#ifndef BINDINGS_GLSL
#define BINDINGS_GLSL
#define CAM_BINDING 0
#define PARTICLE_BINDING 1
#define FFT_DATA_BINDING 2
#define SYSTEM_CONFIG_BINDING 3
#define VISUALIZATION_SETTINGS_BINDING 4
#define HEIGHTS_BINDING 5

#endif // BINDINGS_GLSL
